
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: zuul-getaway
zuul:
  routes:
    service-hi :
      path : /service-hi/*
      serviceId : service-hi
    service-hii :
      path : /service-hii/*
      serviceId : service-hii
